### ISSUE TITLE
Request for admin permissions

### ISSUE THREAD

**Issue by jugmac00** [canonical/txfixtures#28]
After pinging all previous contributors in https://github.com/testing-cabal/txfixtures/issues/19 it looks like this project is currently only used by Canonical for the Launchpad project.

The Launchpad team is willing to take over maintainership, and we have already created a number of pull requests to get this project into shape again.

Currently, from the Launchpad team, only I (@jugmac00) have maintainer permissions, which means only I can merge pull requests. I also cannot add new maintainers myself.

@jelmer Would you please consider to grant admin permissions to:

- @jugmac00 (currently able to merge PRs, but not to administrate this project)
- @ineesalmeida
- @simonepelosi
- @lgp171188
- @sn3rd
- @RuinedYourLife

or at least to me so I can grant the permissions to my colleagues?

Thank you!

**Comment by jelmer** [comment]
Perhaps we should just transfer it to the canonical org?

**Comment by jugmac00** [comment]
@jelmer I had the same idea. I will get some feedback internally and get back to you. Thanks!

**Comment by tushar5526** [comment]
Hi @jelmer , we can proceed with moving the project under Canonical org. For that, you will have to create a transfer request of this project to Canonical and the folks at Canonical will accept it. 

Thanks!

**Comment by jelmer** [comment]
@tushar5526 I can't transfer anything to Canonical, since I'm not a member of that group

**Comment by jugmac00** [comment]
@jelmer Thanks for your support! The transfer worked flawlessly.
